### ISSUE TITLE
"make run" issue

### ISSUE THREAD

**Issue by chillcurve** [raceychan/learncpp_pdf#2]
Thank you for the scrap tool.

Everything works fine except when I do "make run," I keep getting the error below using Windows 11 WSL Ubuntu 24.04.

Log after "make run."

https://ibb.co/4S3b6p3

**Comment by raceychan** [comment]
> Thank you for the scrap tool.
> 
> 
> 
> Everything works fine except when I do "make run," I keep getting the error below using Windows 11 WSL Ubuntu 24.04.
> 
> 
> 
> Log after "make run."
> 
> 
> 
> https://ibb.co/4S3b6p3                                                                                                                                                   

---update

It just came across my mind that I didn't mention you need to install wkhtmltopdf first, would you please run
1. run 'sudo apt-get install wkhtmltopdf' 
2. run 'make run'

-----

Hi there;
Thank you for reporting this issue, the logs suggests that, even though HTMLs were downloaded, they can't be converted to PDFs for unknown reason. 

However, I can't reproduce this issues on my computer of env windows 11 WSL Ubuntu, so i added some extra logs to the newest version of the repo, would you re-clone the repo and paste what's in your errorlog? you might use the new --showerrors options to directly read them in your console.

You might also just re-run the whole program without applying cached files using 'pixi run python -m book --all', since 'make run' would use cached files, and those files might be corrupted.

Either way, keep me updated and I am more than happy to help.

**Comment by chillcurve** [comment]
Hello,

Yes, it works now with wkhtmltopdf installation.

Thank you for your help.
